const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const authRoutes = require('./routes/auth');
const adminRoutes = require('./routes/admin');
const memberRoutes = require('./routes/member');
const app = express();
app.use(cors()); app.use(bodyParser.json());
app.use('/auth', authRoutes); app.use('/admin', adminRoutes); app.use('/member', memberRoutes);
app.get('/', (req, res) => res.send('Absensi backend running'));
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => console.log(`Server started on port ${PORT}`));
